title: Michelle Chan # GIS Projects
logo: "https://pbs.twimg.com/profile_images/1222602884807831552/bxavpPQ8_400x400.jpg" # https://pbs.twimg.com/profile_images/1222602884807831552/bxavpPQ8_400x400.jpgyour photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Senior studying Geography and Environmental Science at UMBC. 
  <br><br>
  Certificate in GIS. 
  <br><br>
  <a href="https://www.linkedin.com/in/michelle-chan-bab659124">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
