title: Michelle Chan # GIS Projects
logo: "https://gm1.ggpht.com/4bwbzqPCVikhCQwnG9r2NkaMPLzVqXsJkGFSls-RYUATJqEx4dRDfYQyVAIArYyuffLl1wTJqdecXMNd9AexPwteIWiYUtHR9iaenYRDQRt_n1O_sLlK1blvMOlUUxuKeqcoEApH021NVHXmbTlKDF-_hi9kZ_EtpXvZnpH64MA8-wGFpI4_U5eZll9r7TRQAmfwzTa5DBUQ5WhKCUItctQ97CMQUMxj7IyAOORzla3zoftDxLt5Uh6qyCy9a3jHo89RxFV2dPGNu-IbBeEU2AU9Dt1m8IL-6Z3z0E4G8-Xn3ogKg1XvgNnZhfV5lXE2OCKOrtpDna0Zx7hBGoONoQc8Gn7EONRtZwrJzeKhTdTPfr29FWmNXqRzgfy7pahkx5bT9grWF64_JqDEwKPX_HFbUqYdfWj4GjArOLcdHC6tn0CHPDZIgYGrbwWoJeMNw2pNffV7k0L_wFlhpWMedoxWxDoJ8qHISd4Gl9TL7D3tp2dsHcQurZ24XfAyObdzaqsxcZ0vv6hWX-R52oQPDKPBvoay3nAHuUrYoypP15Rr2gX-Sk5-Mupg8vi2_wZbsr4iyC_y6a7TnD0_QJRmxTo04t-gA86_mK6lxSlej76E2FwUk7crt0IZdpCmS676I4XcXTLjmCcSMK04TvVPDiWV2GMWfx9LYiXkuDVBG4Uz21kfWE46C3_grJ7PKJ17QPStEbg1Z6BcH0rxo-eEnSnfq7qDVxJRyqc3LLsLLFe7oQiN1iCcGjc6Jq6h=s0-l75-ft-l75-ft" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Senior studying Geography and Environmental Science at UMBC. 
  <br><br>
  Certificate in GIS. 
  <br><br>
  <a href="https://www.linkedin.com/in/michelle-chan-bab659124">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
